export const reviewText = [
  "Amy C. — 5 stars. 6/2/2025. ...while in my home, they were respectful (I didn't even have to ask them to remove their shoes!), methodically precise, informative and they went above and beyond to help me with a couple of other lighting needs. They are both so friendly and authentic. I'm sharing their contact info with my neighbors, friends and family. Highly recommend!",
  "Justin G. — 5 stars. 4/28/2025. Igor and Peter were incredible. Came to my house quickly, were communicative, and wanted to help me as best they could without knowing what the actual problem was. They were thorough and you could tell they wanted to do a good job. Super grateful and will definitely be using them again the next time I have electrical needs.",
  "Karthik S. — 5 stars. 5/7/2025. Igor did a very intelligent set up to power my subpanel from my generator when others wanted to replace my entire main panel. Knowledgeable in the trade, reasonable in pricing and punctual in timing! That’s Igor.",
  "Lindsay H. — 5 stars. 5/10/2025. Igor is reliable and excellent! Communicating with him was easy and he was able to fix everything we needed. He even repaired an issue we'd be having for years that other electricians hadn't been able to help us with. His prices were very fair. I won't use anyone else!",
  "Lorraine B. — 5 stars. 3/23/2025. ...when they came to give us a quote, we decided to do some extra things that had been bugging us- extra lighting in rooms that were poorly lit. Their prices were fair and competitive, their work was exemplary and they were punctual. The job was done within a few days of the quote. I would highly recommend them and use them again should the need arise.",
  "Marilyn N. — 5 stars. 4/20/2025. Igor and Peter did a whole electrical rewiring of our house and added additional lights, outlets, etc. They were reliable, communicative, and very easy to work with. Highly recommend!",
  "Michael K. — 5 stars. 3/13/2025. Igor did a full panel upgrade (110 amp –> 220 amp) without any issues! Even corrected the work from his old company’s coworkers too! He also added a 220 Volt electric vehicle outlet and run a decently long conduit to my folks original electric panel without any issues! It’s too easy to work with him! Great quality jobs! Super highly recommended!",
  "Robin G. — 5 stars. 5/26/2025. ...I was so impressed at how they accomplished this task. Putting in an EV charger in my condo is almost impossible, but they did it. If it weren’t for the care they took it could have turned out disastrous. Other electricians have drilled right through conduit embedded on the inter floor concrete. Meter Electric was awesome. I highly recommend them on every count.",
  "Adkins A. — 5 stars. 3/4/2025. I called meter electric for a generator install after the recent power outage/s there have been around this area. They were very friendly and helpful answering all my questions throughout the process. Turns out I got one installed just in time before another outage in late February here.... Excellent quality work and reasonable price as well. Highly recommend these guys!",
  "Sarah L. — 5 stars. 3/5/2025. ...he was prompt and communicative, handled the permit submission, on time and did an incredible job. Not only that, but he and his sons took time to check all our wiring, test all breakers, add in additional outlets and walk us through all of the updates and improvements. He was upfront about what was actually necessary, versus some of the other electricians we felt were trying to scare you into additional work. He also removed the old service mast and filled in the holes, leaving the area clean and tidy. Would absolutely recommend and hire Meter Electric again.",
  "Spence R. — 5 stars. 3/7/2025. This electrician is highly skilled, deeply knowledgeable, and exceptionally dedicated to their work. I’ve worked with Igor on many projects and will continue to use him on all of my remodels.",
];
